language: python
# sudo: enabled or required
python:
 - "3.9.2"

branches:
  only:
  - master

install:
 - pip install -r local_requirements.txt

before_script:
 - flake8 app tests
 - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD

script:
 - python app/main.py
 - docker build -t nymrli/python:v2 .

after_success:
 - docker push
 - echo "success"


services:
 - docker
