language: python
# sudo: enabled
python:
 - "3.9.1"

install:
 - pip install -r local_requirements.txt

before_script:
 - flake8 app tests


script:
 - python app/main.py


after_success:
 - echo "success"